[project]
name = "url-shortener"
version = "0.1.0"
description = ""
authors = [
    {name = "Negar Yeganeh",email = "negaryeganeh2004@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv (>=1.2.1,<2.0.0)",
    "sqlalchemy (>=2.0.45,<3.0.0)",
    "alembic (>=1.17.2,<2.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "schedule (>=1.2.2,<2.0.0)",
    "fastapi (>=0.124.2,<0.125.0)",
    "uvicorn (>=0.38.0,<0.39.0)",
    "apscheduler (>=3.11.1,<4.0.0)"
]

[tool.poetry.scripts]
url-shortener = "main:run_server"
url-cleanup = "app.commands.cleanup:cleanup_expired_links"
url-scheduler = "app.scheduler.ttl_scheduler:start_ttl_scheduler"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
